# general settings
name: EHLT_SRx3
model_type: EHLTModel
scale: 3
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: ./datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: ./datasets/DIV2K/DIV2K_train_LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set5/HR
    dataroot_lq: ./datasets/Set5/LR_bicubic/X4
    io_backend:
      type: disk


network_g:
  type: EHLT
  upscale: 3
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  alpha: 0.5
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~
  param_key_g: 'params_ema'


# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-1
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 480000]
    gamma: 0.5


  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 4000
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: fasle
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
